version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: mi_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres-db

  dbt:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dbt_container
    volumes:
      - ./ecommerce_dbt:/app/ecommerce_dbt
      - ./dbt_profiles:/root/.dbt
    depends_on:
      - postgres-db
    command: tail -f /dev/null   

volumes:
  postgres_data:
